"""empty message

Revision ID: 45b12378e15f
Revises: 74d7f7997e90
Create Date: 2022-02-14 23:49:45.604134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45b12378e15f'
down_revision = '74d7f7997e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('factura_client_id_fkey', 'factura', type_='foreignkey')
    op.create_foreign_key(None, 'factura', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('factura_detalle_factura_id_fkey', 'factura_detalle', type_='foreignkey')
    op.create_foreign_key(None, 'factura_detalle', 'factura', ['factura_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'factura_detalle', type_='foreignkey')
    op.create_foreign_key('factura_detalle_factura_id_fkey', 'factura_detalle', 'factura', ['factura_id'], ['id'])
    op.drop_constraint(None, 'factura', type_='foreignkey')
    op.create_foreign_key('factura_client_id_fkey', 'factura', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
