"""empty message

Revision ID: 941e19070ba0
Revises: 2807edd385a2
Create Date: 2022-02-06 21:09:53.624866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941e19070ba0'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fiscal_id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('doc', sa.String(length=100), nullable=False),
    sa.Column('num_fac', sa.String(length=100), nullable=False),
    sa.Column('lin_fac', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('emisor', sa.String(length=100), nullable=False),
    sa.Column('emisor_id', sa.String(length=100), nullable=False),
    sa.Column('receptor', sa.String(length=100), nullable=False),
    sa.Column('receptor_id', sa.String(length=100), nullable=False),
    sa.Column('moneda', sa.String(length=100), nullable=False),
    sa.Column('actividad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('user_Client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('factura_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('detalle', sa.String(length=100), nullable=False),
    sa.Column('tarifa', sa.Integer(), nullable=False),
    sa.Column('precio_unit', sa.Float(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=100), nullable=False),
    sa.Column('gravado_isc', sa.Float(), nullable=False),
    sa.Column('exento_isc', sa.Float(), nullable=False),
    sa.Column('imp_especif', sa.Float(), nullable=False),
    sa.Column('monto_linea', sa.Float(), nullable=False),
    sa.Column('gravado', sa.Float(), nullable=False),
    sa.Column('exento', sa.Float(), nullable=False),
    sa.Column('exonerado', sa.Float(), nullable=False),
    sa.Column('si_otro', sa.Float(), nullable=False),
    sa.Column('descuento', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('monto_isc', sa.Float(), nullable=False),
    sa.Column('impuesto', sa.Float(), nullable=False),
    sa.Column('mon_total', sa.Float(), nullable=False),
    sa.Column('auto_exon', sa.String(length=100), nullable=False),
    sa.Column('fecha_exon', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['factura.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factura_id')
    )
    op.add_column('user', sa.Column('apellido', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('nombre', sa.String(length=250), nullable=False))
    op.add_column('user', sa.Column('rol', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rol')
    op.drop_column('user', 'nombre')
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'apellido')
    op.drop_table('factura_detalle')
    op.drop_table('user_Client')
    op.drop_table('factura')
    op.drop_table('client')
    # ### end Alembic commands ###
